version: 2.1

orbs:
  github-maven-deploy: github-maven-deploy/github-maven-deploy@1.0.3

mvn-build-test-command: &mvn-build-test-command
  mvn-build-test-command: mvn clean package -PbuildKar

mvn-collect-artifacts-command: &mvn-collect-artifacts-command
  mvn-collect-artifacts-command: |
    find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;

mvn-deploy-command: &mvn-deploy-command
  mvn-deploy-command: mvn -s .maven.xml clean deploy -PbuildKar -DdeployAtEnd=true -DperformRelease=true -DskipTests -Dspotbugs.skip=true
  context: rso

workflows:
  workflow:
    jobs:
      - github-maven-deploy/build-and-test:
          <<: *mvn-build-test-command
          #@todo Fix test results saved to artifacts/junit dir
          #<<: *mvn-collect-artifacts-command

      - github-maven-deploy/approve-deploy-patch-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test
      - github-maven-deploy/approve-deploy-minor-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test
      - github-maven-deploy/approve-deploy-major-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test
      - github-maven-deploy/deploy-patch-version:
          requires:
            - github-maven-deploy/approve-deploy-patch-version
          <<: *mvn-deploy-command
      - github-maven-deploy/deploy-minor-version:
          requires:
            - github-maven-deploy/approve-deploy-minor-version
          <<: *mvn-deploy-command
      - github-maven-deploy/deploy-major-version:
          requires:
            - github-maven-deploy/approve-deploy-major-version
          <<: *mvn-deploy-command
